spring:
  aop:
    auto: true
    proxy-target-class: true
  application:
    name: jWt-serve
  datasource:
    #数据源基本配置
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud?useSSL=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
       ## 最小空闲连接数量
      minimum-idle: 5
       ## 连接池最大连接数
      maximum-pool-size: 15
       ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
       ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
       ## 连接池母子
      pool-name: MyHikariCP
       ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
       # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 18800
       ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
      host: 127.0.0.1
      port: 6379
      timeout: 5000 #连接超时 毫秒
      jedis:
        pool:
          maxActive: 3
          maxIdle: 3
          minIdle: 1
          maxWait: -1 #连接池最大等行时间 -1没有限制
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*/*.xml,classpath:mybatis/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.own.jwtserve.mvc.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
   # refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8096
  servlet:
      context-path: /auth
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
      prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
      ip-address: ${IP_ADDRESS:127.0.0.1}
      instance-id: ${spring.application.name}:${server.port} #指定实例id
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 2000  #请求连接的超时时间
  ReadTimeout: 2000 #请求处理的超时时间

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #断路器的超时时间,下级服务返回超出熔断器时间，即便成功，消费端消息也是TIMEOUT,所以一般断路器的超时时间需要大于ribbon的超时时间
#Hystrix 开启断路器
feign:
  hystrix:
    enabled: true

#Hystrix Dashboard断路面板配置
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
own:
  jwt:
    secret: own@Login(Auth}*^31)&own% # 登录校验的密钥
    pubKeyPath: d:\\tmp\\rsa\\rsa.pub # 公钥地址
    priKeyPath: d:\\tmp\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
    cookieMaxAge: 30
    header: token



auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: XcWebApp
  clientSecret: XcWebApp
  cookieDomain: xuecheng.com
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/xc.keystore
    secret: xuechengkeystore
    alias: xckey
    password: xuecheng

jwt:
  auth:
    path: login-security
